### DISCUSSION TITLE
Structured Facts

### DISCUSSION THREAD

**Discussion by jortel** [konveyor/enhancements#127] [Ideas]
There is a requirement to display structured fact values using UI widgets instead of raw YAML.
The fact value is first and foremost data and its value just not be diluted with _display_ information.

The simplest and most flexible approach is for the UI to inspect the structure and match it to one of its supported types.
- string
- int
- map
- Array of string  -  Single column table.
- Single: Array of map  - Table with each key in the map as a column.
- Multiple: Array of map  - Tab (for each key) each containing a table.

Display YAML when structure not matched.

#### Example Fact=JPA  

has a structure of 2 tabs (Session Factory, Entities) each containing a table.

```
---
sessionFactory:
  - name: JTA-unit
    configuration: test-app.war/MTA-INF/persistence.xml
    version: 2
entities:
  - name: Thing
    entity: file://entity.xml
```
